{% set name = "inplace-abn" %}
{% set version = "1.1.0" %}

{% if cuda_compiler_version in (None, "None", True, False) %}
{% set cuda_major = 0 %}
{% else %}
{% set cuda_major = environ.get("cuda_compiler_version", "11.8").split(".")[0] | int %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/inplace-abn-{{ version }}.tar.gz
  sha256: 7c286ca53d35cb37b0d1f8b9beb5a910c694129d3d4f7b8e53188370bb260c27

build:
  number: 12
  skip: true  # [win]
  {% if cuda_major < 12 %}
  skip: true  # [cuda_compiler_version != "None"]
  {% endif %}
  string: cpu_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
  string: cuda{{ cuda_compiler_version | replace('.', '') }}_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ compiler("cuda") }}  # [cuda_compiler_version != "None"]
    - {{ stdlib("c") }}
    - cuda-toolkit            # [cuda_compiler_version != "None" and build_platform != target_platform]
  host:
    # GPU requirements
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    - cuda-toolkit                              # [cuda_compiler_version != "None"]
    - pip
    - python
    - pytorch >=2.4.0
    - setuptools
    - setuptools-scm
  run:
    - cuda-cudart  # [cuda_compiler_version != "None"]
    - python

test:
  imports:
    - inplace_abn
  commands:
    - pip check
  requires:
    - pip
    - setuptools

about:
  home: https://github.com/mapillary/inplace_abn
  summary: In-Place Activated BatchNorm for Memory-Optimized Training of DNNs
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
